services:
  postgres:
    image: postgres:17-alpine
    container_name: zzic-postgres
    environment:
      POSTGRES_DB: zzic
      POSTGRES_USER: zzic
      POSTGRES_PASSWORD: zzic
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: zzic-redis

volumes:
  postgres_data:
