services:
  zzic:
    image: ghcr.io/get-to-the-point/zzic-api:latest
    container_name: zzic-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zzic.rule=Host(`zzic-api.xiyo.dev`)"
      - "traefik.http.routers.zzic.entrypoints=websecure"
      - "traefik.http.routers.zzic.tls.certresolver=cloudflare"
      - "traefik.http.services.zzic.loadbalancer.server.port=8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - web
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - web

networks:
  web:
    external: true