services:
  database:
    image: bitnami/postgresql:latest
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=zzic
    volumes:
      - postgresql-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgresql-data:
    driver: local