services:
  postgres:
    image: postgres:16-alpine
    container_name: zzic-postgres
    ports:
      - "5432:5432"           # 로컬에서 접속할 수 있도록 포트 매핑
    environment:
      POSTGRES_DB: zzic
      POSTGRES_USER: zzic
      POSTGRES_PASSWORD: zzic
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: zzic-redis
    ports:
      - "6379:6379"           # 로컬에서 접속할 수 있도록 포트 매핑

volumes:
  postgres_data: