spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      connect-timeout: 1000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 1000ms
          max-idle: 8
          min-idle: 0
