app:
  scheme: https
  host: zzic-api.xiyo.dev
  port: 443

jwt:
  private-key: classpath:zzic/jwt/test-private.pem
  public-key: classpath:zzic/jwt/public.pem
  key-id: rsa-key-id
  access-token:
    expiration: 60
    cookie:
      name: access-token
      domain: xiyo.dev
      path: /
      secure: true
      httpOnly: false
      sameSite: lax
  refresh-token:
    expiration: 31536000
    cookie:
      name: refresh-token
      domain: xiyo.dev
      path: /
      secure: true
      httpOnly: true
      sameSite: lax
