spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zzic
    driver-class-name: org.postgresql.Driver
    username: zzic
    password: zzic
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update