jwt:
  private-key: classpath:zzic/jwt/test-private.pem
  public-key: classpath:zzic/jwt/public.pem
  key-id: rsa-key-id
  access-token:
    expiration: 60
    cookie:
      name: access-token
      domain: 
      path: /
      secure: true
      httpOnly: false
      sameSite: lax
  refresh-token:
    expiration: 31536000
    cookie:
      name: refresh-token
      domain: 
      path: /
      secure: true
      httpOnly: true
      sameSite: lax

server:
  port: 8443
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:zzic/jwt/test-zzic.p12
    key-store-type: PKCS12
    key-store-password: 
    key-alias: zzic-api
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
