spring:
  application:
    name: zzic-api

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:25432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /