spring:
  application:
    name: zzic-api
  profiles:
    group:
      dev:
        - "db-h2"
        - "common-dev"
      prod:
        - "db-pg"
        - "redis"
        - "common-prod"
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages
    encoding: UTF-8

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /v3/api-docs