jwt:
  private-key: classpath:zzic/jwt/test-private.pem
  public-key: classpath:zzic/jwt/public.pem
  key-id: rsa-key-id
  access-token:
    expiration: 60
    cookie:
      name: access-token
      domain: localhost
      path: /
      secure: false
      httpOnly: false
      sameSite: none
  refresh-token:
    expiration: 31536000
    cookie:
      name: refresh-token
      domain: localhost
      path: /
      secure: false
      httpOnly: true
      sameSite: none

server:
  http2:
    enabled: true

logging:
  level:
    root: debug