spring:
  application:
    name: zzic-api

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev