spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  private-key: ${JWT_PRIVATE_KEY:classpath:zzic/jwt/test-private.pem}
  public-key: ${JWT_PUBLIC_KEY:classpath:zzic/jwt/public.pem}
  key-id: ${JWT_KEY_ID:rsa-key-id}
  expiration: ${JWT_EXPIRATION:60}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:31536000}
  access-token:
    cookie:
      name: access-token
      domain: ${JWT_COOKIE_DOMAIN:xiyo.dev}
      path: /
      secure: true
      httpOnly: false
      sameSite: lax
  refresh-token:
    cookie:
      name: refresh-token
      domain: ${JWT_COOKIE_DOMAIN:xiyo.dev}
      path: /
      secure: true
      httpOnly: true
      sameSite: lax

server:
  port: 443
  ssl:
    key-store: classpath:zzic/jwt/test-zzic.p12
    key-store-type: PKCS12
    key-store-password:
    key-alias: zzic-api

logging:
  level:
    org.springframework: WARN
    point.zzicback: INFO
