spring:
  application:
    name: zzic-api

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver