name: release-please

on:
  push:
    branches:
      - main  # 기본 브랜치에서 실행

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 또는 PAT 사용 가능
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json