name: Semantic Versioning & Build

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 전체 Git 히스토리(태그 포함)

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Determine Next Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          tag_prefix: "v"
          bump_each_commit: false

      - name: Update build version in gradle.properties
        if: steps.version.outputs.new_version != ''
        run: |
          echo "version=${{ steps.version.outputs.new_version }}" > gradle.properties

      - name: Commit version bump
        if: steps.version.outputs.new_version != ''
        run: |
          git add gradle.properties
          git commit -m "🔖 Bump version to ${{ steps.version.outputs.new_version }}"
          git tag -a v${{ steps.version.outputs.new_version }} -m "Release ${{ steps.version.outputs.new_version }}"
          git push origin main --tags

  build:
    runs-on: ubuntu-latest
    needs: versioning
    if: needs.versioning.outputs.new_version != ''
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build Project
        run: ./gradlew build -x test