name: Java Build Only

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build Project
        run: ./gradlew build -x test