name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version
        id: extract_version
        run: |
          version=$(cat gradle.properties | cut -d'=' -f2)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image (ARM64)
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/get-to-the-point/zzic-api:${{ steps.extract_version.outputs.version }}
            ghcr.io/get-to-the-point/zzic-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.HOST }}
          port: ${{ vars.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/Projects/zzic-api
            docker compose pull
            docker compose up -d