name: Release Please

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 태그, 릴리즈 생성 권한 부여
      pull-requests: write  # 자동 PR 생성 권한 부여
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple  # 기본적인 버전 관리
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Release Outputs
        run: echo "New version is ${{ steps.release.outputs.release_version }}"

      # Gradle 버전 업데이트
      - name: Update version in gradle.properties
        if: steps.release.outputs.release_created == 'true'
        run: |
          echo "version=${{ steps.release.outputs.release_version }}" > gradle.properties
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gradle.properties
          git commit -m "🔖 Bump version to ${{ steps.release.outputs.release_version }}"
          git push origin main

      - name: Build Project
        if: steps.release.outputs.release_created == 'true'
        run: ./gradlew build -x test