name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Test and Build
      run: |
        chmod +x ./gradlew
        ./gradlew clean test bootJar --no-daemon

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ghcr.io/get-to-the-point/zzic-api:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.ED25519 }}
        script: |
          cd ~/Projects/zzic-api && \
          echo "현재 디렉토리: $(pwd)" && \
          echo "Docker Compose 파일 확인..." && \
          ls -la docker-compose* && \
          echo "최신 이미지 Pull..." && \
          docker compose pull zzic-api && \
          echo "서비스 재시작..." && \
          docker compose up -d --force-recreate zzic-api && \
          echo "배포 완료!" && \
          docker compose ps
