name: "Java Build & Test"

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행
  pull_request:
    branches:
      - main  # PR이 main으로 들어올 때 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  test-java:
    runs-on: ubuntu-latest  # GitHub 기본 환경 (Ubuntu)

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4  # 코드 가져오기

      - name: ☕ Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'  # Amazon Corretto (자바 21 지원)
          java-version: '21'

      - name: 🔧 Set up Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: 🏗️ Build & Run Tests
        run: |
          chmod +x gradlew
          ./gradlew clean test --no-daemon